function Hd = filter_design(B, OSR, GB)
%FILTER_DESIGN Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 24.2 and DSP System Toolbox 24.2.
% Generated on: 22-Mar-2025 13:38:15

% Equiripple Lowpass filter designed using the FIRPM function.

% All frequency values are in Hz.
Fs = B*OSR;  % Sampling Frequency

Fpass = B/2;               % Passband Frequency
Fstop = GB/2;              % Stopband Frequency
Dpass = 0.00057564620966;  % Passband Ripple
Dstop = 0.031622776602;    % Stopband Attenuation
dens  = 20;                % Density Factor

% Calculate the order from the parameters using FIRPMORD.
[N, Fo, Ao, W] = firpmord([Fpass, Fstop]/(Fs/2), [1 0], [Dpass, Dstop]);

% Calculate the coefficients using the FIRPM function.
b  = firpm(N, Fo, Ao, W, {dens});
Hd = dfilt.dffir(b);

% [EOF]
